package gui;
import dao.VueloDAO;
import modelo.Reserva;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Vuelo;
import java.util.List; 
import java.sql.SQLException; 
import java.time.LocalDate;

/**
 *
 * @author sebas
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private VueloDAO vueloDAO;
    /**
     * Creates new form VentanaPrincipal
     */
    
    
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.vueloDAO = new VueloDAO();
        cargarDatosTabla(); 
    }

    private void cargarDatosTabla() {
    try {
        // Lógica para obtener los datos y llenar la tabla
        java.util.List<modelo.Vuelo> vuelos = this.vueloDAO.getVuelos();
    } catch (java.sql.SQLException e) {
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnActualizarVuelos = new javax.swing.JButton();
        btnConfirmarReserva = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestion de vuelos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Listado de vuelos disponibles");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID vuelo", "Origen", "Destino", "Fecha Salida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnActualizarVuelos.setText("Actualizar vuelos");
        btnActualizarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarVuelosActionPerformed(evt);
            }
        });

        btnConfirmarReserva.setText("Reservar");
        btnConfirmarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarReservaActionPerformed(evt);
            }
        });

        btnCrearUsuario.setText("Crear usuario");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });

        btnReservas.setText("Ver reservas realizadas");
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(btnConfirmarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizarVuelos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrearUsuario)
                        .addGap(8, 8, 8)
                        .addComponent(btnConfirmarReserva)
                        .addGap(34, 34, 34)
                        .addComponent(btnReservas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarVuelosActionPerformed
    try {
            // Llama al método getVuelos() a través del objeto 'vueloDAO'
            List<Vuelo> vuelos = this.vueloDAO.getVuelos();

            // Crea un modelo de tabla para cargar los datos
            DefaultTableModel modeloTabla = new DefaultTableModel();
            
            // Define las columnas de la tabla
            modeloTabla.addColumn("ID Vuelo");
            modeloTabla.addColumn("Origen");
            modeloTabla.addColumn("Destino");
            modeloTabla.addColumn("Fecha Salida");

            // Itera sobre la lista de vuelos obtenida y añade cada uno al modelo de la tabla
            for (Vuelo vuelo : vuelos) {
                modeloTabla.addRow(new Object[]{
                    vuelo.getIdVuelo(),
                    vuelo.getOrigen(),
                    vuelo.getDestino(),
                    vuelo.getFechaSalida()
                });
            }
            
            // Asigna el modelo lleno a tu JTable (ajusta el nombre de la variable de tu tabla si es necesario)
            // Por ejemplo, si tu JTable se llama 'miTablaVuelos', sería 'miTablaVuelos.setModel(modeloTabla);'
            jTable1.setModel(modeloTabla);

        } catch (SQLException e) {
            // Muestra un mensaje de error si hay un problema con la base de datos
            JOptionPane.showMessageDialog(this, "Error al cargar los vuelos: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnActualizarVuelosActionPerformed

    private void btnConfirmarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarReservaActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un vuelo de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    int idVuelo = (int) jTable1.getModel().getValueAt(filaSeleccionada, 0);
    VentanaReserva reservaDialog = new VentanaReserva(this, true, idVuelo);
    reservaDialog.setVisible(true);
    
    // Refresh the table after the dialog closes
    cargarDatosTabla();
    }//GEN-LAST:event_btnConfirmarReservaActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        VentanaPasajero pasajeroDialog = new VentanaPasajero(this, true);
    pasajeroDialog.setVisible(true);
    
    // Obtiene el ID del pasajero recién creado cuando el diálogo se cierra
    int idPasajero = pasajeroDialog.getIdPasajeroCreado();
    
    if (idPasajero != -1) {
        JOptionPane.showMessageDialog(this, "Ahora puedes usar el ID " + idPasajero + " para hacer una reserva.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        VentanaReservasRealizadas reservasDialog = new VentanaReservasRealizadas(this, true);
        reservasDialog.setVisible(true);


    }//GEN-LAST:event_btnReservasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarVuelos;
    private javax.swing.JButton btnConfirmarReserva;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
